# Generated by Django 4.2.23 on 2025-08-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('src_ip', models.GenericIPAddressField()),
                ('dest_ip', models.GenericIPAddressField()),
                ('dest_port', models.IntegerField(blank=True, null=True)),
                ('signature', models.CharField(max_length=255)),
                ('anomaly_score', models.IntegerField(default=0)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('geoip_country', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_reputation', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
